#!/usr/bin/python

import smtplib
import getopt
import sys

from email.mime.text import MIMEText
SMTP_SERVER = "smtp.mail.yahoo.com"
SMTP_PORT = 587
SMTP_USERNAME = "minions777@yahoo.com"
SMTP_PASSWORD = "GruR0cks!"
EMAIL_FROM = "minions777@yahoo.com"
EMAIL_TO = ""
EMAIL_SUBJECT = ""
co_msg = ""

def send_email(EMAIL_FROM, EMAIL_TO, EMAIL_SUBJECT, co_msg):
    print EMAIL_FROM + " " + EMAIL_TO + " " + EMAIL_SUBJECT + " " + co_msg
    msg = MIMEText(co_msg)
    msg['Subject'] = EMAIL_SUBJECT 
    msg['From'] = EMAIL_FROM 
    msg['To'] = EMAIL_TO
    debuglevel = True
    mail = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
    mail.set_debuglevel(debuglevel)
    mail.starttls()
    mail.login(SMTP_USERNAME, SMTP_PASSWORD)
    mail.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())
    mail.quit()

def formatMsg(msg):
    newMsg = "THIS IS AN AUTOGENERATED MESSAGE. DO NOT REPLY\n\n\n" 
    newMsg = newMsg + "Master,\n\n"
    newMsg = newMsg + msg + "\n\n"
    newMsg = newMsg + "--Your Minion"
    return newMsg

def usage():
   print sys.argv[0] + " -t <to email addr> -s <subj> -m <msg>"
   print "Use -h or --help for options"

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "ho:vt:s:m:f:", ["help", "output="])
    except getopt.GetoptError as err:
        # print help information and exit:
        print str(err) # will print something like "option -a not recognized"
        usage()
        sys.exit(2)
    output = None
    verbose = False
    fr = None
    to = None
    subj = None
    msg = None
    for o, a in opts:
        if o == "-v":
            verbose = True
        elif o in ("-h", "--help"):
            usage()
            sys.exit()
        elif o in ("-o", "--output"):
            output = a
        elif o in ("-f"):
            fr = a
        elif o in ("-t"):
            to = a
        elif o in ("-s"):
            subj = a
        elif o in ("-m"):
            msg = a
        else:
            assert False, "unhandled option"
    EMAIL_SUBJECT = "[Minions] " + subj
    EMAIL_TO = to
    co_msg = formatMsg(msg)
    send_email(EMAIL_FROM, EMAIL_TO, EMAIL_SUBJECT, co_msg)
 

if __name__=='__main__':
    main()

